# Generated by Django 3.2.6 on 2021-08-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_leader', to='students.student'),
        ),
    ]
