# Generated by Django 3.2.6 on 2021-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_group_group_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title',), 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('fio', 'group'), 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
