# Generated by Django 3.2.6 on 2021-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210817_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_About_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('model_create', models.CharField(blank=True, max_length=255)),
                ('model_editing', models.CharField(blank=True, max_length=255)),
                ('model_delete', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
